### ISSUE TITLE
Restarting Slack changes active workspace

### ISSUE THREAD

**Issue by dadrian** [cdzombak/restart-slack#3]
If you're in a fullscreen app and Slack restarts, the active workspace changes to whatever desktop has Slack. Is this preventable? I would try to fix but I know nothing about AppleScript.

**Comment by cdzombak** [comment]
Hmm. I'm not totally sure how to fix this, and I don't use multiple workspaces myself. 

The AppleScript uses the `open` tool to open Slack in the background, and that's just part of OS X (not AppleScript specific). Perhaps the `open` man page is a place to start.

**Comment by dadrian** [comment]
Well, you already pass `-g`, so it look like this is a spaces issue. I'm trying changing the System Preference described at http://apple.stackexchange.com/questions/4801/how-can-i-stop-spaces-from-switching-automatically

**Comment by cdzombak** [comment]
> Well, you already pass `-g`, so it look like this is a spaces issue.

After looking at the manpage myself, I'd agree here.

> I'm trying changing the System Preference described at http://apple.stackexchange.com/questions/4801/how-can-i-stop-spaces-from-switching-automatically

This one, right?

```
defaults write com.apple.Dock workspaces-auto-swoosh -bool NO
```

Please let me know how this works. If it's working for you I'll add it to the README.

**Comment by dadrian** [comment]
This system preference does not seem to work :/

**Comment by cdzombak** [comment]
Hm 😞 

One more idea, which will keep Slack on all your spaces but might prevent this changing of workspace, would be to assign Slack to "All Desktops":

<img width="409" alt="screen shot 2016-07-26 at 09 40 52" src="https://cloud.githubusercontent.com/assets/102904/17140094/2802487e-5315-11e6-89f9-e88cc89f6274.png">

If you try that and it works, please let me know. I don't have anything else to recommend, other than "stop using Spaces".

**Comment by dadrian** [comment]
I don't even seem to have that option on my Slack dock icon. Regardless, I'm going to chalk this up to "not Chris's problem", and give up. If the Slack app wasn't an awful memory hog, we wouldn't be in this situation anyway.

Thanks for the help!

**Comment by cdzombak** [comment]
Sorry I couldn't provide any more help 😞
