### ISSUE TITLE
Slack does not open again

### ISSUE THREAD

**Issue by PercussiveRepair** [cdzombak/restart-slack#4]
Installed the components and edited the plist file as per README.
The script successfully quits Slack when not in the foreground, but Slack fails to start again. 
Running the script manually using the Mac Script Editor gives: 
`Result:
error "Slack got an error: User canceled." number -128
`
Running OSX 10.11.6 & Slack 2.8.0 (Beta Channel)

**Comment by cdzombak** [comment]
Huh, that's something I haven't seen before. I'm no longer maintaining this software, but I have two suggestions for things to try:

* Try running the command `open -ga /Applications/Slack.app` manually, to see if it works (an dSlack opens) on its own.
* Try increasing the `delay` in the AppleScript, from `7` to something like `15`.

**Comment by PercussiveRepair** [comment]
Thanks for the reply. I understand that this is something of a throwaway project! 
Thanks for the tips. Tried both of those already :)

**Comment by PercussiveRepair** [comment]
No bother. Thanks!
